### ISSUE TITLE
switch.send_command bug

### ISSUE THREAD

**Issue by aysun168** [syssi/chuangmi_ir#13]
`Error executing service <ServiceCall switch.send_command_192_168_31_19 (c:c01a18be5e8a4e828198de5fbaa0a084): command=['Z6VHADgCAACVBgAAvwgAAG8RAABDIwAAYiMAALyYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1ABAAABAQAAAQABAQAAAQEBAAAAAQEBAAABAQEAAAABBgJAA=']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1177, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "/config/custom_components/switch/chuangmi_ir.py", line 115, in _send_command
    ir_remote.play_raw(command, 38400)
  File "/config/deps/lib/python3.6/site-packages/miio/chuangmi_ir.py", line 64, in play_raw
    {'freq': frequency, 'code': command})
  File "/config/deps/lib/python3.6/site-packages/miio/device.py", line 270, in send
    raise DeviceError(m.data.value["error"])
miio.exceptions.DeviceError: {'code': -5008, 'message': 'magic error'}`

script
`aotuma_on:
    sequence:
      - service: switch.send_command_192_168_31_19
        data:
          command:
            - 'Z6VHADgCAACVBgAAvwgAAG8RAABDIwAAYiMAALyYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1ABAAABAQAAAQABAQAAAQEBAAAAAQEBAAABAQEAAAABBgJAA='`

`switch:
  - platform: chuangmi_ir
    name: "Living Room IR Remote"
    host: 192.168.31.19
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    switches:
      x9s:
        command_on: 'Z6VLAEMCAAB/BgAAnwgAAIsRAAAvIwAAsLMAAMh3AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAEAAAAAAAAAAQABAAEBAAABAAABAAABAQABBQJGAkAA==' #开机
        command_off: 'Z6VLAEMCAAB/BgAAnwgAAIsRAAAvIwAAsLMAAMh3AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAEAAAAAAAAAAQABAAEBAAABAAABAAABAQABBQJGAkAA==' #关机`
学习命令没有问题，现在无法发出命令
Home Assistant
0.79 -- 0.79.3这几个版本都有问题

**Comment by syssi** [comment]
Please capture the infrared command again and update your configuration. The "magic error" appears if you command cannot be re-played.

**Comment by aysun168** [comment]
The script could not issue the command，
'aotuma_on: sequence: - service: switch.send_command_192_168_31_19 data: command: - 'Z6VHADgCAACVBgAAvwgAAG8RAABDIwAAYiMAALyYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1ABAAABAQAAAQABAQAAAQEBAAAAAQEBAAABAQEAAAABBgJAA='
Any questions about this notation?

**Comment by aysun168** [comment]
Relearning still doesn't work

**Comment by aysun168** [comment]
重新安装了，树莓派安装RASPBIAN STRETCH LITE系统，没有任何问题了，之前用的是DIETPI
