### ISSUE TITLE
Getting 96 char not 32...

### ISSUE THREAD

**Issue by Caboz** [syssi/chuangmi_ir#5]
When I read the Tokens in my xiaomi IR I'm getting a 96 char string not a 32 as it is expected.

I have 4 IR devices like this and all have 96 char tokens.

**Comment by syssi** [comment]
The iOS app has introduced encrypted 96 char tokens recently. I found a way to decrypt the token. You can use this tool: https://github.com/rytilahti/python-miio#miio-extract-tokens

**Comment by syssi** [comment]
If you are familiar with python you can use this code snippet:

https://community.home-assistant.io/t/xiaomi-gateway-integration/8213/3052?u=syssi
https://community.home-assistant.io/t/xiaomi-gateway-integration/8213/3056?u=syssi

**Comment by Caboz** [comment]
Thanks!!!!

I ended up using: http://aes.online-domain-tools.com/

and 00000000000000000000000000000000 as the Key (hex)
